Fix Calendar View Issue
ohcnetwork/leaderboard pull request #559
Opened 2024-12-14 07:15 UTC by JavidSumra

## Fixes #550 
## Changes
- Updated the Array Size for Calendar Data According to the size of JSON Object Key Values in

2024-12-16 07:30 UTC, rithviknishad requested changes

2024-12-16 07:30 UTC, rithviknishad commented on components/contributors/ActivityCalendarGitHub.tsx
> +  const [year, setYear] = useState(new Date().getFullYear());
The reason why we kept this as 0 is, if no year is selected, we would show past 365 days data. i.e. if we are on Jan 10th, 2025, we'll show Jan 10th 2024 to Jan 10th 2025's data and not just Jan 1st 2025 to Jan 10th 2025.

2024-12-20 06:08 UTC, JavidSumra commented
@rithviknishad can you please review this PR?

2024-12-20 07:35 UTC, rithviknishad requested changes
didn't solve the issue

![image](https://github.com/user-attachments/assets/496b6474-41e5-41d2-b5ee-8cf80a56002c)

![image](https://github.com/user-attachments/assets/1136eb1d-d169-4ab9-bc96-77e39a6cfa7d)

2024-12-20 11:53 UTC, rithviknishad requested changes
this breaks other things; this is not the expected rank list for the last 7 days

<img width="823" alt="image" src="https://github.com/user-attachments/assets/cb163442-cb4a-48da-819f-aa035b0ef87b" />

2025-01-07 11:33 UTC, closed without merging

2025-01-07 11:33 UTC, rithviknishad commented
Closing due to no activity

2025-01-07 11:36 UTC, JavidSumra commented
> Closing due to no activity

@rithviknishad, as per our discussion on Slack, we agreed to revisit this in January. However, since you're currently occupied with the Care frontend, it's not feasible. Could you please reopen it?