Added Functionality to learn more in contributors page (Redirection to GraduteAttribute page)
ohcnetwork/leaderboard pull request #585
Opened 2024-12-30 08:25 UTC by AnveshNalimela

- Fixes #579 
Add 'Learn More' Redirection to Graduate Attribute Page on Contributors Page 
The "Learn More" button on the Contributors page, allowing users to navigate to the Graduate Attribute page for additional details

How to test
- Navigate to the Contributors page.
- Scroll down to  Gradute Attributes section.
- Click the "Learn More" button.
- Confirm redirection to the appropriate Graduate Attribute detail page.

![Screenshot from 2024-12-30 13-50-21](https://github.com/user-attachments/assets/d84f3b1f-a933-4e7c-a312-f654d51c04f2)

![Screenshot from 2024-12-30 13-50-31](https://github.com/user-attachments/assets/9dc0bbe1-864c-4eac-9171-e90dfa47b4bf)

![Screenshot from 2024-12-30 13-50-39](https://github.com/user-attachments/assets/6b0b71f2-17cc-497c-b941-2a67f493bcd4)

Closes #579

2024-12-30 08:45 UTC, AnveshNalimela commented
[Screencast from 2024-12-30 14-14-37.webm](https://github.com/user-attachments/assets/38d903ed-fe41-4b5c-a20c-e67cde4dbeaf)

2025-01-01 08:45 UTC, rithviknishad requested changes
let's keep it similar to how graduate attributes popover is shown at the top. make the popover content reusable too. dedicated page doesn't make sense

btw let's start using shadcn components for achieving this.

2025-01-01 16:19 UTC, rithviknishad commented
we don't need to show all at once, we can show it similar to the badges at the top, which shows popover of one badge on click

2025-01-07 11:40 UTC, rithviknishad approved these changes

2025-01-07 11:41 UTC, merged