Incorrect Year according to Week Display on Leaderboard
ohcnetwork/leaderboard pull request #589
Opened 2024-12-31 07:13 UTC by abhimanyurajeesh

Since we are following the ISO Week Number Calculation, it was supposed to display as **"Week 1 of 2025"** instead of **"Week 1 of 2024"**

The function was supposed correctly identify December 31, 2024 as part of week 1 of 2025 because it falls after the last Thursday of 2024 (which is December 26, 2024). The function works perfectly in getting the week number but fail with the year.

![Bug](https://github.com/user-attachments/assets/08d15609-0160-43ba-bb76-4ae029128a10)

This change ensures that both the week number and year correctly reflect the ISO week date standards, especially at the boundaries between years.

2024-12-31 09:56 UTC, abhimanyurajeesh commented
This will solve the issue.

2024-12-31 09:58 UTC, abhimanyurajeesh commented
![image](https://github.com/user-attachments/assets/aa695a71-a800-4c10-89ad-2f5b5fdff663)

2024-12-31 11:21 UTC, rithviknishad requested changes
Today it should be showing week 52/53 of 2024 instead right?

<img width="1822" alt="image" src="https://github.com/user-attachments/assets/02760464-846d-40a7-8fef-b6679a8e4ce6" />

2024-12-31 12:55 UTC, abhimanyurajeesh commented
According the ISO rule it should be **"Week 1 of 2025"** but your right, it should make sense to common man.

I have made the changes according.

### Updated Code Screenshot
![image](https://github.com/user-attachments/assets/d3eb6f46-2b6f-4486-9c7a-fe8e5d66b0cf)

2024-12-31 13:07 UTC, rithviknishad commented
the right answer for today is, week 53. 

isn't the current logic incorrect? shows 9 entries for week 52 when i tested your logic.

<img width="239" alt="image" src="https://github.com/user-attachments/assets/71079c4d-c719-4411-a86b-850dbc7c0242" />

2025-01-02 05:16 UTC, rithviknishad approved these changes
not a fan of this complicated logic, but works.

2025-01-02 05:16 UTC, merged